name: PR Build

on: [pull_request]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v1
      with:
        submodules: true
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15

    - name: Build Debug
      run: dotnet build Trains.NET.sln -p:CI=true -c Debug -bl:debug.binlog

    - name: Upload debug binary log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: binlog
        path: debug.binlog
        retention-days: 5

    - name: Build Release
      run: dotnet build Trains.NET.sln -p:CI=true -c Release -bl:release.binlog

    - name: Upload release binary log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: binlog
        path: release.binlog
        retention-days: 5

    - name: Run tests
      run: dotnet test Trains.NET.sln

  build-mac:

    runs-on: macos-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v1
    
      - name: setup-xamarin
        uses: maxim-lobanov/setup-xamarin@v1
        with:
          xamarin-mac-version: latest

      - name: Build Debug
        run: msbuild Trains.NET.Mac.sln /r /p:CI=true /p:Configuration=Debug /bl:debug.binlog

      - name: Upload debug binary log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: debug-binlog
          path: debug.binlog
          retention-days: 5

      - name: Build Release
        run: msbuild Trains.NET.Mac.sln /r /p:CI=true /p:Configuration=Release /bl:release.binlog

      - name: Upload release binary log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: release-binlog
          path: release.binlog
          if-no-files-found: ignore
          retention-days: 5
